#!C:\Users\pipek\OneDrive\Documentos\code_folder\DS4A\FE_DS4A\env\Scripts\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
